### PR TITLE
implement structured logging

### LINKED ISSUE #25: [PROPOSAL] Structured logging with -v flag
PIMO need to log what is happening in the stderr file.

The log might be structured with https://github.com/sirupsen/logrus, or (better performance) : https://github.com/rs/zerolog, https://github.com/uber-go/zap

The level of verbosity is passed via the -v flag, the default value (0) does not log anything, the other possible values are : 

1. error : log only errors
2. warn : same as level 1 + warnings that should be checked by user
3. info : same as level 2 + information about what is processed
4. debug : same as level 3 + debugging information, to analyse what can cause an unexpected behavior
5. trace : same as level 4 + tracing of events in code (enter function, exit function)

Example :

```console
$ echo "{}" | pimo -v3 > result.jsonl
INFO[0000] Reading file from disk                      definition=file://.masking.yml
INFO[0000] Begin processing of pipeline                definition=file://.masking.yml
WARN[0000] Ignoring mask because path is non-existent  definition=file://.masking.yml path=name mask=randomInt
```

Logs can be in JSON format with `--log-json` flag 

```console
$ echo "{}" | pimo -v3 --log-json > result.jsonl
{"definition":"file://.masking.yml","level":"info","msg":"Reading file from disk","time":"2014-03-10 19:57:38.562264131 -0400 EDT"}
{"definition":"file://.masking.yml","level":"info","msg":"Begin processing of pipeline","time":"2014-03-10 19:57:38.562264131 -0400 EDT"}
{"definition":"file://.masking.yml","level":"warn","msg":"Ignoring mask because path is non-existent","time":"2014-03-10 19:57:38.562264131 -0400 EDT","path":"name","mask":"randomInt"}
```

### PR DESCRIPTION
**Pull request by adrienaury**
/close #25

### CODE REVIEW

**Comment by adrienaury** [comment]
Currently the logs look like this

```console
$ (cd demo/demo1 && pimo -v5 < data.jsonl)
6:20PM INF Logger level set to trace config=masking.yml
6:20PM INF Start PIMO config=masking.yml
6:20PM DBG Mask constant config=masking.yml data=Dupont line-number=1 path=name
6:20PM DBG Mask randomChoice config=masking.yml data=Martin line-number=1 path=surname
6:20PM DBG Mask hash config=masking.yml data=Nantes line-number=1 path=town
6:20PM DBG Mask randomInt config=masking.yml data=28 line-number=1 path=age
{"age":79,"name":"Benjamin","surname":"Dupont","town":"Ruby City"}
6:20PM DBG Mask constant config=masking.yml data=Dupont line-number=2 path=name
6:20PM DBG Mask randomChoice config=masking.yml data=Martin line-number=2 path=surname
6:20PM DBG Mask hash config=masking.yml data=Nantes line-number=2 path=town
6:20PM DBG Mask randomInt config=masking.yml data=28 line-number=2 path=age
{"age":53,"name":"Benjamin","surname":"Dupont","town":"Ruby City"}
6:20PM DBG Mask constant config=masking.yml data=Dupont line-number=3 path=name
6:20PM DBG Mask randomChoice config=masking.yml data=Martin line-number=3 path=surname
6:20PM DBG Mask hash config=masking.yml data=Nantes line-number=3 path=town
6:20PM DBG Mask randomInt config=masking.yml data=28 line-number=3 path=age
{"age":71,"name":"Benjamin","surname":"Dupond","town":"Ruby City"}
6:20PM DBG Mask constant config=masking.yml data=Dupont line-number=4 path=name
6:20PM DBG Mask randomChoice config=masking.yml data=Martin line-number=4 path=surname
6:20PM DBG Mask hash config=masking.yml data=Nantes line-number=4 path=town
6:20PM DBG Mask randomInt config=masking.yml data=28 line-number=4 path=age
{"age":23,"name":"Benjamin","surname":"Dupont","town":"Ruby City"}
6:20PM DBG Mask constant config=masking.yml data=Dupont line-number=5 path=name
6:20PM DBG Mask randomChoice config=masking.yml data=Martin line-number=5 path=surname
6:20PM DBG Mask hash config=masking.yml data=Nantes line-number=5 path=town
6:20PM DBG Mask randomInt config=masking.yml data=28 line-number=5 path=age
{"age":85,"name":"Benjamin","surname":"Dupond","town":"Ruby City"}
6:20PM INF End PIMO config=masking.yml line-number=5 path= return=0
```

And in json format 

```json
{"level":"info","config":"masking.yml","message":"Logger level set to trace"}
{"level":"info","config":"masking.yml","message":"Start PIMO"}
{"level":"debug","data":"Dupont","config":"masking.yml","line-number":"1","path":"name","message":"Mask constant"}
{"level":"debug","data":"Martin","config":"masking.yml","line-number":"1","path":"surname","message":"Mask randomChoice"}
{"level":"debug","data":"Nantes","config":"masking.yml","line-number":"1","path":"town","message":"Mask hash"}
{"level":"debug","data":28,"config":"masking.yml","line-number":"1","path":"age","message":"Mask randomInt"}
{"level":"debug","data":"Dupont","config":"masking.yml","line-number":"2","path":"name","message":"Mask constant"}
{"level":"debug","data":"Martin","config":"masking.yml","line-number":"2","path":"surname","message":"Mask randomChoice"}
{"level":"debug","data":"Nantes","config":"masking.yml","line-number":"2","path":"town","message":"Mask hash"}
{"level":"debug","data":28,"config":"masking.yml","line-number":"2","path":"age","message":"Mask randomInt"}
{"level":"debug","data":"Dupont","config":"masking.yml","line-number":"3","path":"name","message":"Mask constant"}
{"level":"debug","data":"Martin","config":"masking.yml","line-number":"3","path":"surname","message":"Mask randomChoice"}
{"level":"debug","data":"Nantes","config":"masking.yml","line-number":"3","path":"town","message":"Mask hash"}
{"level":"debug","data":28,"config":"masking.yml","line-number":"3","path":"age","message":"Mask randomInt"}
{"level":"debug","data":"Dupont","config":"masking.yml","line-number":"4","path":"name","message":"Mask constant"}
{"level":"debug","data":"Martin","config":"masking.yml","line-number":"4","path":"surname","message":"Mask randomChoice"}
{"level":"debug","data":"Nantes","config":"masking.yml","line-number":"4","path":"town","message":"Mask hash"}
{"level":"debug","data":28,"config":"masking.yml","line-number":"4","path":"age","message":"Mask randomInt"}
{"level":"debug","data":"Dupont","config":"masking.yml","line-number":"5","path":"name","message":"Mask constant"}
{"level":"debug","data":"Martin","config":"masking.yml","line-number":"5","path":"surname","message":"Mask randomChoice"}
{"level":"debug","data":"Nantes","config":"masking.yml","line-number":"5","path":"town","message":"Mask hash"}
{"level":"debug","data":28,"config":"masking.yml","line-number":"5","path":"age","message":"Mask randomInt"}
{"level":"info","return":0,"config":"masking.yml","line-number":"5","path":"","message":"End PIMO"}
```

**Comment by adrienaury** [comment]
image

**Comment by adrienaury** [comment]
A nice way to present logs 

```console
$ (cd demo/demo2 && pimo --log-json -v5 < data.jsonl >/dev/null 2> >( jq -c . | mlr --ijson --opprint --barred cat))
+-------+-------------+---------------------------+
| level | config      | message                   |
+-------+-------------+---------------------------+
| info  | masking.yml | Logger level set to trace |
| info  | masking.yml | Start PIMO                |
+-------+-------------+---------------------------+

+-------+----------+-------------+-------------+----------+---------------------+
| level | data     | config      | line-number | path     | message             |
+-------+----------+-------------+-------------+----------+---------------------+
| info  | Jean     | masking.yml | 1           | identity | Mask command        |
| info  | Bertrand | masking.yml | 1           | identity | Mask weightedChoice |
| info  | 27       | masking.yml | 1           | identity | Mask randomInt      |
| info  | Nantes   | masking.yml | 1           | town     | Mask randomChoice   |
| info  | Benjamin | masking.yml | 2           | identity | Mask command        |
| info  | Martin   | masking.yml | 2           | identity | Mask weightedChoice |
| info  | 58       | masking.yml | 2           | identity | Mask randomInt      |
| info  | Nantes   | masking.yml | 2           | town     | Mask randomChoice   |
| info  | Benjamin | masking.yml | 3           | identity | Mask command        |
| info  | Bertrand | masking.yml | 3           | identity | Mask weightedChoice |
| info  | 35       | masking.yml | 3           | identity | Mask randomInt      |
| info  | Rennes   | masking.yml | 3           | town     | Mask randomChoice   |
| info  | Jean     | masking.yml | 4           | identity | Mask command        |
| info  | Martin   | masking.yml | 4           | identity | Mask weightedChoice |
| info  | 28       | masking.yml | 4           | identity | Mask randomInt      |
| info  | Rennes   | masking.yml | 4           | town     | Mask randomChoice   |
+-------+----------+-------------+-------------+----------+---------------------+

+-------+--------+-------------+-------------+------+----------+
| level | return | config      | line-number | path | message  |
+-------+--------+-------------+-------------+------+----------+
| info  | 0      | masking.yml | 4           | -    | End PIMO |
+-------+--------+-------------+-------------+------+----------+
```

**Comment by adrienaury** [comment]
Also close #22

**Review by youen — APPROVED** [review]

**Comment by adrienaury** [comment]
To be done

- [ ] Documentation README
- [ ] CHANGELOG
- [ ] Log (warn) when a mask is ignored because the path is not found in the jsonline

**Pull request merged**
