### PR TITLE
Proposal new markov mask

### LINKED ISSUE #54: [Proposal] new markov mask
## Motivation

To generate random string the `regex` mask is limited for small text but can't generate pseudo natural language.

## Solution

Use markov chain [1] to produce pseudo text based on example. Add a new `markov` mask with transitions as parameters

```yaml

mask: 
  markov :
    # protection against infinity loop
    max-size: 20
    parameters:
       - from: "I am"
         to: "a"
         weight : 0.5
       - from: "I am"
         to: "not"
         weight : 0.5
       - from: "am a"
         to: "free"
         weight : 1
      - from: "free"
         to: "man"
         weight : 1

```

Parameters are extremely verbose and should not be compute by human. Parameters should be externalized in a json file.

```yaml
mask: 
  markov :
    # protection against infinity loop
    max-size: 20
    parameters: free-man.json
```

Or better compute from an sample text

```yaml
mask: 
  markov :
    # protection against infinity loop
    max-size: 20
    sample: free-man.txt
```

[1] https://en.wikipedia.org/wiki/Markov_chain#Markov_text_generators

### PR DESCRIPTION
**Pull request by Baguettte**
Markov mask generates pseudo text based on a sample text.

Note: this is a draft pull request, because tests have to be made on more complete/complex sample text. The question of the chain order is also to be discussed.

Closes #54

### CODE REVIEW

**Comment by adrienaury** [comment]
> ```
> --mask "value=[{fluxUri: 'pimo://nameFR'}]"
> ```

If you try :

```
pimo --empty-input --repeat 886 --mask "name=[{fluxUri: 'pimo://nameFR'}]"
```

You will see that after `Zazie` the next value returned by the `fluxUri` mask is `""`.
Why is it like that ?

**Comment by Baguettte** [comment]
> > However, fluxUri keeps the last name Zazie in memory, so repeat-until never ends, and keeps masking using Zazie as a never ending value
> 
> If you try :
> 
> ```
> pimo --empty-input --repeat 886 --mask "name=[{fluxUri: 'pimo://nameFR'}]"
> ```
> 
> You will see that after `Zazie` the next value returned by the `fluxUri` mask is `""`. Why is it different with the repeat-until flag ?



> > However, fluxUri keeps the last name Zazie in memory, so repeat-until never ends, and keeps masking using Zazie as a never ending value
> 
> If you try :
> 
> ```
> pimo --empty-input --repeat 886 --mask "name=[{fluxUri: 'pimo://nameFR'}]"
> ```
> 
> You will see that after `Zazie` the next value returned by the `fluxUri` mask is `""`. Why is it different with the repeat-until flag ?

Comment moved to PR https://github.com/CGI-FR/PIMO/pull/82

**Comment by adrienaury** [comment]
I tested this PR with a few file, for me the results are very good, on correctness and on performances.

What do you mean by 
> The question of the chain order is also to be discussed.

?

**Comment by Baguettte** [comment]
In the current version, I made it constant (equals to 2). I just wonder if it should be a parameter or not. 
What do you think?

(reminder for futur reader: You need to define an order for your markov chain. You know It is used to calculate your probabilities: the probability of state b to occuring will depend on the N previous states in the training chain (N being the order))

**Comment by adrienaury** [comment]
> In the current version, I made it constant (equals to 2). I just wonder if it should be a parameter or not.
> What do you think?

Ah ok!

Yes we should give a way to change this value in the masking.yaml but the value 2 by default.

**Comment by Baguettte** [comment]
Alright I'm changing that.
I'm also focusing on a way to split punctuation as well.

**Comment by adrienaury** [comment]
> Alright I'm changing that.

The parameter can be named `order `

**Comment by adrienaury** [comment]
> I'm also focusing on a way to split punctuation as well.

Could you give an example of this feature ?

**Comment by Baguettte** [comment]
It's not much of a feature. Before this commit https://github.com/CGI-FR/PIMO/pull/81/commits/13d9375b865f366da9b48a4cea0d868d913a3b15, the chain would be built like that:
**sample.txt**
```
Hello, i'm a Golang developer.
```
The mask would separate worlds like that: 
```
["Hello," , "i'm" , "a" , "Golang" , "developer."]
```
IMO the mask should be smarter and consider punctuation as independant words.

In addition i must add a trimspace somwhere to avoid blanks in the chain.

**Comment by Baguettte** [comment]
## Problem
Markov Mask can be used on different samples:
- lists of words 
- paragraphs

For list of words, we would want to read the file line by line (exemples: nameFR, pokemons, etc..)
For entire paragraphs, or text that can be spread over multiple lines.

## Proposal

In addition of the `separator` parameter that determine the way we split the text (word by word, character by character, etc..), we would want a parameter that helps the mask to understand the structure of the text:
- is it a list?
- is it paragraphs?
- is it something else?

Anyway, markov mask should have a default configuration in order not to make it unusable.

**Pull request merged**
